### ISSUE TITLE
data read problem if not all sleep states present 

### ISSUE THREAD

**Issue by brianhtracey** [ChristineBlume/SleepCycles#4]
Hi, first off, thank you for posting this!  Your code is very helpful.

I got a file read error when reading in a sleep scoring file (after many other files ran fine).  In this particular file, there was no stage 3 sleep scored, so there were only 4 sleep states present (0,1,2, and 5).  I think this may have caused a problem because of the check on line 17 of load_prep.R, which checks that length(unique(data[,z])) == 5, so 'cycles' was never assigned.

Would it make sense to instead check that length(unique(data[,z])) <=5?  The next line then checks that it's in the list of recognized states.

I haven't fully debugged this but just wanted to post the question If I'm doing something wrong and the code should be able to handle files where one state is never scored, just let me know!  And, thanks again...

**Comment by ChristineBlume** [comment]
Hi Brian, thanks a lot for the suggestion, which I have implemented. An updated package (1.1.2) is on its way to CRAN. The reason why the code assumes there are five stages is that it is highly unlikely that a whole night of sleep does not have any N3. Therefore, caution is required when interpreting the results and I definitely recommend a visual check of the resulting hypnogram/cycle plots.
